# Generated by Django 2.1 on 2025-06-12 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='金額')),
                ('transactions_type', models.CharField(choices=[('1', '収入'), ('2', '支出')], max_length=1, verbose_name='種別')),
                ('note', models.TextField(max_length=1000, verbose_name='備考')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Payment', verbose_name='支払方法')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='カテゴリ'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
