# Generated by Django 2.1 on 2025-06-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlist', '0003_auto_20250612_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transactions_type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('1', '収入'), ('2', '支出')], max_length=2, null=True, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Payment', verbose_name='支払方法'),
        ),
    ]
