# Generated by Django 2.1 on 2025-06-16 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
                ('category_type', models.CharField(choices=[('1', '収入'), ('2', '支出')], max_length=2, null=True, verbose_name='種別')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='取引日時')),
                ('amount', models.IntegerField(default=0, verbose_name='金額')),
                ('note', models.TextField(blank=True, max_length=1000, verbose_name='備考')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Category', verbose_name='カテゴリ')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='受取/支払方法')),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Types', verbose_name='受取/支払方法'),
        ),
    ]
