# Generated by Django 2.1 on 2025-06-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Expense', verbose_name='支払場面'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=255, verbose_name='受取・支払方法'),
        ),
    ]
