# Generated by Django 2.1 on 2025-06-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetlist', '0002_auto_20250612_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('2', '食費'), ('4', '衣服'), ('6', '交通費'), ('3', '交際費'), ('5', '家賃/生活費'), ('1', '給料')], null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Category'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='note',
            field=models.TextField(blank=True, max_length=1000, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='payment',
            field=models.ForeignKey(blank=True, choices=[('2', 'クレジットカード'), ('1', '現金'), ('3', 'デビットカード')], null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetlist.Payment', verbose_name='支払方法'),
        ),
    ]
